unit Test.UP.Table;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  //rtl
  TestFramework, System.Classes, System.SysUtils,
  //UP
  UP.Table, UP.Base, UP.Client, UP.Database;

type
  TUPFakeClient = class(TInterfacedObject, IUPClient)
  strict private
    FCommand: IUPCommand;
    FResult: IUPResult;
  public
    function ExecuteCommand(Command: IUPCommand): IUPResult;
    function Command: IUPCommand;
    function Result: IUPResult;
  end;

  TUPTest = class abstract(TTestCase)
  private
    FCredentials: IUPCredentials;
    FClient: IUPClient;
  public
    procedure SetUp; override;
    function Client: TUPFakeClient;
  end;

  TestIUPFields = class(TTestCase)
  published
    procedure TestGet;
    procedure TestDelete;
    procedure TestAdd;
    procedure TestImmutable;
  end;

  TestIUPTable = class(TTestCase)
  published
    procedure TestFields;
    procedure TestImmutable;
  end;

implementation

{ TUPFakeClient }

function TUPFakeClient.Command: IUPCommand;
begin
  Result := FCommand;
end;

function TUPFakeClient.ExecuteCommand(Command: IUPCommand): IUPResult;
begin
  FCommand := Command;
  Result := TUPResult.New('OK');
end;

function TUPFakeClient.Result: IUPResult;
begin
  Result := FResult;
end;

{ TUPTest }

function TUPTest.Client: TUPFakeClient;
begin
  Result := FClient as TUPFakeClient;
end;

procedure TUPTest.SetUp;
begin
  inherited;
  FCredentials := TUPCredentials.New(
      'localhost/3051:E:\Bancos\OS 3776\WSAC.FDB',
      'SYSDBA',
      'masterkey',
      'FB'
  );
  FClient := TUPFakeClient.Create;
end;

{ TestIUPFields }

procedure TestIUPFields.TestAdd;
var
  vTable: IUPTable;
begin
  vTable := T
end;

procedure TestIUPFields.TestDelete;
begin

end;

procedure TestIUPFields.TestGet;
begin

end;

procedure TestIUPFields.TestImmutable;
begin

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestIUPFields.Suite);
  RegisterTest(TestIUPTable.Suite);
end.

